import Head from "next/head";
import { getSession, useSession } from "next-auth/react";

import { Sidebar, Feed, Login } from "../components";

export default function Home({ trendingResults, followResults }) {
  const { data: session } = useSession({ required: true });

  return (
    <div>
      <Head>
        <title>Twither</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        {/* Widgets  */}

        {/* Modal */}
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }
  const trendingResults = await fetch(
    "https://jsonkeeper.com/b/NKEV"
  ).then((res) => res.json());
  const followResults = await fetch(
    "https://jsonkeeper.com/b/WWMJ"
  ).then((res) => res.json());
  return {
    props: {
      trendingResults,
      followResults,
      session,
    },
  };
};
